"""
Created by MNS, Summer 2023
Dedicated to my friends with the intention of wreaking havoc in our discord servers.
"""

class Settings:
    BOOST_PROBABILITY_VALUE = 0
    RESPOND_SWEAR_MESSAGE_PROBABILITY = 100
    RESPONSE_FAMILY_INSULT_ADDITION_PROBABILITY = 30

    EARRAPE_AFTERNOON_PROBABILITY = BOOST_PROBABILITY_VALUE + 15
    EARRAPE_EVENING_PROBABILITY = BOOST_PROBABILITY_VALUE + 20
    EARRAPE_NIGHT_PROBABILITY = BOOST_PROBABILITY_VALUE + 25
    EARRAPE_MORNING_NOON_PROBABILITY = BOOST_PROBABILITY_VALUE + 10
    EARRAPE_MATCHING_TIME_PROBABILITY = BOOST_PROBABILITY_VALUE + 99

    DEAFEN_MUTE_PROBABILITY = 5
    DEAFEN_MUTE_SLEEP_TIME_SECONDS = 10
    REQUIRED_MEMBERS_FOR_DEAFEN_MUTE = 2

    RESPOND_TO_OTHER_BOT_PROBABILITY = 3
    MENTION_SWEARING_USER_PROBABILITY = 10

    TARGET_BULLYING_VOICE_KICK_PROBABILITY = 20
    TARGET_BULLYING_VOICE_KICK_DELAY = 2

    MIX_CHANNELS_PROBABILITY = 3
    MIX_CHANNELS_MIN_MEMBERS = 3